Document: ser2sock
Title: Debian ser2sock Manual
Author: <insert document author here>
Abstract: This manual describes what ser2sock is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/ser2sock/ser2sock.sgml.gz

Format: postscript
Files: /usr/share/doc/ser2sock/ser2sock.ps.gz

Format: text
Files: /usr/share/doc/ser2sock/ser2sock.text.gz

Format: HTML
Index: /usr/share/doc/ser2sock/html/index.html
Files: /usr/share/doc/ser2sock/html/*.html
